<div class="row main_banner">
	<div class="col-sm-12">
		<a href="<?php echo Mage::getBaseUrl() ?>home-and-garden/push-sweepers.html">
			<img src="<?php echo $this->getSkinUrl('images/home/pushsweepers.jpg')?>" class="img-responsive">
			<span class="overlay_yellow">
				<span>PUSH SWEEPERS</span>
				<button class="btn btn-primary">Know More</button>
			</span>
		</a>
	</div>
</div>
<div class="row top_30 main_banner">
	<div class="col-sm-6">
		<a href="<?php echo Mage::getBaseUrl() ?>home-and-garden/vacuums.html">
			<img src="<?php echo $this->getSkinUrl('images/home/vaccum_cleaners.jpg')?>" class="img-responsive">
			<span class="overlay_green_light">
				<span>VACUUM CLEANERS</span>
				<button class="btn btn-primary">Know More</button>
			</span>
		</a>
	</div>
	<div class="col-sm-6">
		<a href="<?php echo Mage::getBaseUrl() ?>home-and-garden/extractors.html">
			<img src="<?php echo $this->getSkinUrl('images/home/extractors.jpg')?>" class="img-responsive">
			<span class="overlay_blue">
				<span>EXTRACTORS</span>
				<button class="btn btn-primary">Know More</button>
			</span>
		</a>
	</div>
</div>
<div class="row top_30 main_banner">
	<div class="col-sm-12">
		<a href="<?php echo Mage::getBaseUrl() ?>professional/pressure-washers.html">
			<img src="<?php echo $this->getSkinUrl('images/home/card1.jpg')?>" class="img-responsive">
			<span class="overlay_yellow">
				<span>PRESSURE WASHERS</span>
				<button class="btn btn-primary">Know More</button>
			</span>
		</a>
	</div>
</div>
