<div class="row top_30 main_banner">
	<div class="col-sm-12">
		<a href="<?php echo Mage::getBaseUrl() ?>professional/pressure-washers.html">
			<img src="<?php echo $this->getSkinUrl('images/home/card1.jpg')?>" class="img-responsive">
			<span class="overlay_yellow">
				<span>PRESSURE WASHERS</span>
				<button class="btn btn-primary">Know More</button>
			</span>
		</a>
	</div>
</div>
<div class="row top_30 main_banner">
	<div class="col-sm-6">
		<a href="#">
			<img src="<?php echo $this->getSkinUrl('images/home/card3.jpg')?>" class="img-responsive">
			<span class="overlay_blue">
				<span>FLOOR SCRUBBER</span>
				<button class="btn btn-primary">Know More</button>
			</span>
		</a>
	</div>
	<div class="col-sm-6">
		<a href="#">
			<img src="<?php echo $this->getSkinUrl('images/home/vaccum_cleaners.jpg')?>" class="img-responsive">
			<span class="overlay_green_light">
				<span>VACCUM CLEANERS</span>
				<button class="btn btn-primary">Know More</button>
			</span>
		</a>
	</div>

</div>
