<div class="row main_banner">
	<div class="col-sm-12">
		<a href="#">
			<img src="<?php echo $this->getSkinUrl('images/home/home_banner.jpg')?>" class="img-responsive">
			<span class="overlay">
				<span>A pure pleasure.</span> 
				<span class="small_heading">Simply clean with no drips</span>
				<button class="btn btn-primary">Know More</button>
			</span>
		</a>
	</div>
</div>
<div class="row top_30 main_banner">
	<div class="col-sm-7">
		<a href="<?php echo Mage::getBaseUrl() ?>professional/pressure-washers.html">
			<img src="<?php echo $this->getSkinUrl('images/home/card1.jpg')?>" class="img-responsive">
			<span class="overlay_yellow">
				<span>PRESSURE WASHERS</span>
				<button class="btn btn-primary">Know More</button>
			</span>
		</a>
	</div>
	<div class="col-sm-5">
		<a href="#">
			<img src="<?php echo $this->getSkinUrl('images/home/card2.jpg')?>" class="img-responsive">
			<span class="overlay_brown">
				<span>PUSH SWEEPERS</span>
				<button class="btn btn-primary">Know More</button>
			</span>
		</a>
	</div>
</div>
<div class="row top_30 main_banner">
	<div class="col-sm-4">
		<a href="#">
			<img src="<?php echo $this->getSkinUrl('images/home/card3.jpg')?>" class="img-responsive">
			<span class="overlay_blue">
				<span>FLOOR SCRUBBER</span>
				<button class="btn btn-primary">Know More</button>
			</span>
		</a>
	</div>
	<div class="col-sm-8">
		<div class="row">
			<div class="col-sm-12">
				<a href="#">
					<img src="<?php echo $this->getSkinUrl('images/home/card4.jpg')?>" class="img-responsive">
					<span class="overlay_violet">
						<span>VACCUM CLEANERS</span>
						<button class="btn btn-primary">Know More</button>
					</span>
				</a>
			</div>
			<div class="col-sm-12 top_30">
				<a href="#">
					<img src="<?php echo $this->getSkinUrl('images/home/card5.jpg')?>" class="img-responsive">
					<span class="overlay_reddish">
						<span>STEAM CLEANERS</span>
						<button class="btn btn-primary">Know More</button>
					</span>
				</a>
			</div>
		</div>
	</div>

</div>
