<div class="row main_banner">
	<div class="col-sm-12">
		<a href="<?php echo Mage::getBaseUrl() ?>professional/pressure-washers.html">
			<img src="<?php echo $this->getSkinUrl('images/home/pressure_washer_second.jpg')?>" class="img-responsive">
			<span class="overlay_yellow">
				<span>PRESSURE WASHERS</span>
				<button class="btn btn-primary">Know More</button>
			</span>
		</a>
	</div>
</div>
<div class="row top_30 main_banner">
	<div class="col-sm-4">
		<a href="<?php echo Mage::getBaseUrl() ?>professional/scrubbers.html">
			<img src="<?php echo $this->getSkinUrl('images/home/scrubber.jpg')?>" class="img-responsive">
			<span class="overlay_blue overlay_small">
				<span>SCRUBBER</span>
				<button class="btn btn-primary">Know More</button>
			</span>
		</a>
	</div>
	<div class="col-sm-4">
		<a href="<?php echo Mage::getBaseUrl() ?>professional/sweepers.html">
			<img src="<?php echo $this->getSkinUrl('images/home/sweeper.jpg')?>" class="img-responsive">
			<span class="overlay_brown_left overlay_small">
				<span>SWEEPERS</span>
				<button class="btn btn-primary">Know More</button>
			</span>
		</a>
	</div>
	<div class="col-sm-4">
		<a href="<?php echo Mage::getBaseUrl() ?>professional/vacuums.html">
			<img src="<?php echo $this->getSkinUrl('images/home/industrial_vaccum.jpg')?>" class="img-responsive">
			<span class="overlay_black_left overlay_small">
				<span>VACUUMS</span>
				<button class="btn btn-primary">Know More</button>
			</span>
		</a>
	</div>

</div>
<div class="row top_30 main_banner">
	<div class="col-sm-4">
		<a href="<?php echo Mage::getBaseUrl() ?>professional/carpet-cleaners.html">
			<img src="<?php echo $this->getSkinUrl('images/home/carpet_cleaners.jpg')?>" class="img-responsive">
			<span class="overlay_carpet overlay_small">
				<span>CARPET CLEANERS</span>
				<button class="btn btn-primary">Know More</button>
			</span>
		</a>
	</div>
	<div class="col-sm-4">
		<a href="<?php echo Mage::getBaseUrl() ?>professional/municipal-equipment.html">
			<img src="<?php echo $this->getSkinUrl('images/home/municipal.jpg')?>" class="img-responsive">
			<span class="overlay_brown_right overlay_small">
				<span>MUNICIPAL EQUIPMENTS</span>
				<button class="btn btn-primary">Know More</button>
			</span>
		</a>
	</div>
	<div class="col-sm-4">
		<a href="<?php echo Mage::getBaseUrl() ?>professional/steam-cleaners-and-speciality.html">
			<img src="<?php echo $this->getSkinUrl('images/home/steam.jpg')?>" class="img-responsive">
			<span class="overlay_black_right overlay_small">
				<span>STEAM CLEANERS AND ACCESSORIES</span>
				<button class="btn btn-primary">Know More</button>
			</span>
		</a>
	</div>

</div>
