<!-- Home Page Slider -->
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
    	<a href="<?php echo Mage::getBaseUrl() ?>professional/pressure-washers.html">
			<img src="<?php echo $this->getSkinUrl('images/home/pressure_washer_banner.jpg')?>" class="img-responsive">
    	</a>
    </div>
    <div class="item">
      <a href="<?php echo Mage::getBaseUrl() ?>professional/vacuums.html">
			<img src="<?php echo $this->getSkinUrl('images/home/vaccum_cleaner_banner.jpg')?>" class="img-responsive">
    	</a>
    </div>
    <div class="item">
      <a href="<?php echo Mage::getBaseUrl() ?>ab-84-cul.html">
			<img src="<?php echo $this->getSkinUrl('images/home/air_mover.jpg')?>" class="img-responsive">
    	</a>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="fa fa-angle-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="fa fa-angle-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="row main_banner">
	<div class="col-sm-12">
		<a href="<?php echo Mage::getBaseUrl() ?>home-and-garden.html">
			<img src="<?php echo $this->getSkinUrl('images/home/home_banner.jpg')?>" class="img-responsive">
			<span class="overlay">
				<span>HOME AND GARDEN</span> 
				<!-- <span class="small_heading">Simply clean with no drips</span> -->
				<button class="btn btn-primary">Know More</button>
			</span>
		</a>
	</div>
</div>
<div class="row top_30 main_banner">
	<div class="col-sm-12">
		<a href="<?php echo Mage::getBaseUrl() ?>professional.html">
			<span class="overlay left_overlay">
				<span>INDUSTRIAL PRODUCTS</span> 
				<!-- <span class="small_heading">Simply clean with no drips</span> -->
				<button class="btn btn-primary">Know More</button>
			</span>
			<img src="<?php echo $this->getSkinUrl('images/home/industrial_home_banner.jpg')?>" class="img-responsive">
		</a>
	</div>
</div>
<div class="row top_30 main_banner">
	<div class="col-sm-7">
		<a href="<?php echo Mage::getBaseUrl() ?>parts-and-accessories.html">
			<img src="<?php echo $this->getSkinUrl('images/home/parts_and_accessories.jpg')?>" class="img-responsive">
			<span class="overlay_yellow_landing">
				<span>PARTS AND ACCESSORIES</span>
				<button class="btn btn-primary">Know More</button>
			</span>
		</a>
	</div>
	<div class="col-sm-5">
		<a href="#">
			<img src="<?php echo $this->getSkinUrl('images/home/manual_and_datasheet.jpg')?>" class="img-responsive">
			<span class="overlay_brown">
				<span>MANUALS AND DATASHEETS</span>
				<button class="btn btn-primary">Know More</button>
			</span>
		</a>
	</div>
</div>
