<div class="row main_banner">
	<div class="col-sm-12">
		<a href="<?php echo Mage::getBaseUrl() ?>home-and-garden.html">
			<img src="<?php echo $this->getSkinUrl('images/home/home_banner.jpg')?>" class="img-responsive">
			<span class="overlay">
				<span>HOME AND GARDEN</span> 
				<!-- <span class="small_heading">Simply clean with no drips</span> -->
				<button class="btn btn-primary">Know More</button>
			</span>
		</a>
	</div>
</div>
<div class="row top_30 main_banner">
	<div class="col-sm-12">
		<a href="<?php echo Mage::getBaseUrl() ?>professional.html">
			<span class="overlay left_overlay">
				<span>INDUSTRIAL PRODUCTS</span> 
				<!-- <span class="small_heading">Simply clean with no drips</span> -->
				<button class="btn btn-primary">Know More</button>
			</span>
			<img src="<?php echo $this->getSkinUrl('images/home/industrial_home_banner.jpg')?>" class="img-responsive">
		</a>
	</div>
</div>
<div class="row top_30 main_banner">
	<div class="col-sm-7">
		<a href="<?php echo Mage::getBaseUrl() ?>parts-and-accessories.html">
			<img src="<?php echo $this->getSkinUrl('images/home/parts_and_accessories.jpg')?>" class="img-responsive">
			<span class="overlay_yellow">
				<span>PARTS AND ACCESSORIES</span>
				<button class="btn btn-primary">Know More</button>
			</span>
		</a>
	</div>
	<div class="col-sm-5">
		<a href="#">
			<img src="<?php echo $this->getSkinUrl('images/home/manual_and_datasheet.jpg')?>" class="img-responsive">
			<span class="overlay_brown">
				<span>MANUALS AND DATASHEETS</span>
				<button class="btn btn-primary">Know More</button>
			</span>
		</a>
	</div>
</div>
