<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/portfolio.css',array('_secure'=>true));?>" />
 <form action="<?php echo $this->getSubmitUrl($_product, array('_secure' => $this->_isSecure())) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
<section class="product_intro">
      <div class="container">
        <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
          <div class="row">
              <div class="col-sm-7">
                  <div class="header-content">
                      <div class="header-content-inner">
                            <?php if ($_product->getDescription()):?>
                                  <p><?php echo $_helper->productAttribute($_product, nl2br($_product->getDescription()), 'description') ?></p>
                            <?php endif;?>
  
                           <div class="add-to-cart-wrapper">
                              <?php echo $this->getChildHtml('product_type_data') ?>
                              <?php echo $this->getChildHtml('extrahint') ?>

                              <?php if (!$this->hasOptions()):?>
                                  <div class="add-to-box">
                                      <?php if($_product->isSaleable()): ?>
                                          <?php echo $this->getChildHtml('addtocart') ?>
                                      <?php endif; ?>
                                  </div>
                              <?php elseif (!$_product->isSaleable()): ?>
                                  <div class="add-to-box">
                                      <?php echo $this->getChildHtml('sharing') ?>
                                  </div>
                              <?php endif; ?>
                          </div>
                      </div>
                  </div>
              </div>
              <div class="col-sm-5">
                  <div class="device-container">
                          <div class="device">
                              <div class="screen">
                                  <!-- Demo image for screen mockup, you can put an image here, some HTML, an animation, video, or anything else! -->
                                  <img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->keepFrame(false); ?>" class="img-responsive" alt="">
                              </div>
                          </div>
                  </div>
              </div>
          </div>
      </div>
  </section>

  <section id="features" class="features">
          <div class="container">
              <div class="row">
                  <div class="col-lg-12 text-center">
                      <div class="section-heading">
                          <h2>Addon Cool Features</h2>
                          <p class="text-muted">These cool features make it number #1 in ranking with others</p>
                          <hr>
                      </div>
                  </div>
              </div>
              <div class="row">
                  <div class="col-md-4">
                      <div class="device-container">
                          <div class="device-mockup iphone6_plus portrait white">
                              <div class="device">
                                  <div class="screen">
                                      <!-- Demo image for screen mockup, you can put an image here, some HTML, an animation, video, or anything else! -->
                                      <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false); ?>" class="img-responsive" alt="">
                                    </div>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div class="col-md-8">
                      <div class="container-fluid">
                          <div class="row">
                              <div class="col-md-4">
                                  <div class="feature-item">
                                      <i class="icon-screen-smartphone text-primary"></i>
                                      <h4>Protection class, II</h4>
                                  </div>
                              </div>
                              <div class="col-md-4">
                                  <div class="feature-item">
                                      <i class="icon-camera text-primary"></i>
                                      <h4>Sturdy plastic casing</h4>
                                  </div>
                              </div>
                              <div class="col-md-4">
                                  <div class="feature-item">
                                      <i class="icon-camera text-primary"></i>
                                      <h4>Handle, Folding</h4>
                                  </div>
                              </div>

                          </div>
                          <div class="row">
                              <div class="col-md-4">
                                  <div class="feature-item">
                                      <i class="icon-present text-primary"></i>
                                      <h4>Chassis</h4>
                                  </div>
                              </div>
                              <div class="col-md-4">
                                  <div class="feature-item">
                                      <i class="icon-lock-open text-primary"></i>
                                      <h4>Ergonomic carrying handle</h4>
                                  </div>
                              </div>
                              <div class="col-md-4">
                                  <div class="feature-item">
                                      <i class="icon-lock-open text-primary"></i>
                                      <h4>Speed settings, 3</h4>
                                  </div>
                              </div>
                          </div>
                          <div class="row">
                              <div class="col-md-4">
                                  <div class="feature-item">
                                      <i class="icon-lock-open text-primary"></i>
                                      <h4>On-board power cable storage</h4>
                                  </div>
                              </div>
                              <div class="col-md-4">
                                  <div class="feature-item">
                                      <i class="icon-lock-open text-primary"></i>
                                      <h4>Carpet clip</h4>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div class="row">
                <div class="col-sm-12 text-center">
                  <div class="add-to-cart-wrapper">
                              <?php echo $this->getChildHtml('product_type_data') ?>
                              <?php echo $this->getChildHtml('extrahint') ?>

                              <?php if (!$this->hasOptions()):?>
                                  <div class="add-to-box">
                                      <?php if($_product->isSaleable()): ?>
                                          <?php echo $this->getChildHtml('addtocart') ?>
                                      <?php endif; ?>
                                  </div>
                              <?php elseif (!$_product->isSaleable()): ?>
                                  <div class="add-to-box">
                                      <?php echo $this->getChildHtml('sharing') ?>
                                  </div>
                              <?php endif; ?>
                          </div>
                </div>
              </div>
    </section>


    <section id="download" class="download bg-primary text-center">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <h2>Great Specifications</h2>
                    
                    
                  <!-- Specification -->
                  <div class="col-sm-12 specificaton">
                    <div class="row">
                      <?php
                        $diameter = $_helper->productAttribute($_product, nl2br($_product->getDiameter()), 'diameter_inches');
                        if($diameter != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/diameter.svg">
                        </div>
                        <div class="specification_features">Diameter</div>
                        <div class="value_specification"><?php echo $_helper->productAttribute($_product, nl2br($_product->getDiameterInches()), 'diameter_inches') ?> inches</div>
                      </div>
                      <?php endif; ?>

                      <?php
                        $psi = $_helper->productAttribute($_product, nl2br($_product->getPsi()), 'psi');
                        if($psi != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/working_pressure.svg">
                        </div>
                        <div class="specification_features">Max. working pressure - PSI</div>
                        <div class="value_specification"><?php echo $_product->getAttributeText('psi'); ?></div>
                      </div>
                      <?php endif; ?>

                      <?php
                        $water_flow_rate_gpm = $_helper->productAttribute($_product, nl2br($_product->getWaterFlowRateGpm()), 'water_flow_rate_gpm');
                        if($water_flow_rate_gpm != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/flow_rate.svg">
                        </div>
                        <div class="specification_features">Water Flow Rate - GPM</div>
                        <div class="value_specification"><?php echo $_helper->productAttribute($_product, nl2br($_product->getWaterFlowRateGpm()), 'water_flow_rate_gpm') ?></div>
                      </div>
                      <?php endif; ?>

                      <!-- Equiment Type -->
                      <?php
                        $equipment_type = $_helper->productAttribute($_product, nl2br($_product->getEquipmentType()), 'equipment_type');
                        if($equipment_type != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/equipment_type.svg">
                        </div>
                        <div class="specification_features">Equipment Type</div>
                        <div class="value_specification"><?php echo $_product->getAttributeText('equipment_type'); ?></div>
                      </div>
                      <?php endif; ?>

                      <!-- Max. Temperature - in Fahrenheit -->

                      <?php
                        $max_temperature = $_helper->productAttribute($_product, nl2br($_product->getMaxTemperature()), 'max_temperature');
                        if($max_temperature != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/temp.svg">
                        </div>
                        <div class="specification_features">Max. Temperature - in Fahrenheit</div>
                        <div class="value_specification"><?php echo $max_temperature; ?></div>
                      </div>
                      <?php endif; ?>

                      <!-- Power Type -->
                      <?php
                        $power_type = $_helper->productAttribute($_product, nl2br($_product->getPowerType()), 'power_type');
                        if($power_type != '') :
                      ?>
                        <div class="col-sm-3">
                          <div class="specification_box">
                            <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/power.svg">
                          </div>
                          <div class="specification_features">Power Type</div>
                          <div class="value_specification"><?php echo $_product->getAttributeText('power_type'); ?></div>
                        </div>
                      <?php endif; ?>

                      <!-- Portable Or Stationary -->
                      <?php
                        $portable_or_stationary = $_helper->productAttribute($_product, nl2br($_product->getPortableOrStationary()), 'portable_or_stationary');
                        if($portable_or_stationary != '') :
                      ?>
                        <div class="col-sm-3">
                          <div class="specification_box">
                            <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/portable.svg">
                          </div>
                          <div class="specification_features">Portable Or Stationary</div>
                          <div class="value_specification"><?php echo $portable_or_stationary ?></div>
                        </div>
                      <?php endif; ?>

                      <!-- Heating Type -->
                      <?php
                        $heating_type = $_helper->productAttribute($_product, nl2br($_product->getHeatingType()), 'heating_type');
                        if($heating_type != '') :
                      ?>
                        <div class="col-sm-3">
                          <div class="specification_box">
                            <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/heating.svg">
                          </div>
                          <div class="specification_features">Heating Type</div>
                          <div class="value_specification"><?php echo $heating_type ?></div>
                        </div>
                      <?php endif; ?>

                      <!-- Ship Weight lbs. -->
                      <?php
                        $ship_weight_lbs = $_helper->productAttribute($_product, nl2br($_product->getShipWeightLbs()), 'ship_weight_lbs');
                        if($ship_weight_lbs != '') :
                      ?>
                        <div class="col-sm-3">
                          <div class="specification_box">
                            <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/weight.svg">
                          </div>
                          <div class="specification_features">Ship Weight lbs.</div>
                          <div class="value_specification"><?php echo $ship_weight_lbs ?></div>
                        </div>
                      <?php endif; ?>

                      <!-- Maximum RPM -->
                      <?php
                        $maximum_rpm = $_helper->productAttribute($_product, nl2br($_product->getMaximumRpm()), 'maximum_rpm');
                        if($maximum_rpm != '') :
                      ?>
                        <div class="col-sm-3">
                          <div class="specification_box">
                            <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/rpm.svg">
                          </div>
                          <div class="specification_features">Maximum RPM</div>
                          <div class="value_specification"><?php echo $maximum_rpm ?></div>
                        </div>
                      <?php endif; ?>

                      <!-- Pump -->
                      <?php
                        $pump = $_helper->productAttribute($_product, nl2br($_product->getPump()), 'pump');
                        if($pump != '') :
                      ?>
                        <div class="col-sm-3">
                          <div class="specification_box">
                            <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/pump.svg">
                          </div>
                          <div class="specification_features">Pump</div>
                          <div class="value_specification"><?php echo $pump ?></div>
                        </div>
                      <?php endif; ?>

                      <!-- Electrical -->
                      <?php
                        $electrical = $_helper->productAttribute($_product, nl2br($_product->getElectrical()), 'electrical');
                        if($electrical != '') :
                      ?>
                         <div class="col-sm-3">
                          <div class="specification_box">
                            <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/electrical.svg">
                          </div>
                          <div class="specification_features">Electrical</div>
                          <div class="value_specification"><?php echo $electrical ?></div>
                        </div>
                      <?php endif; ?>

                         <!-- CC -->
                      <?php
                        $cc = $_helper->productAttribute($_product, nl2br($_product->getCc()), 'cc');
                        if($cc != '') :
                      ?>
                        <div class="col-sm-3">
                          <div class="specification_box">
                            <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/cc.svg">
                          </div>
                          <div class="specification_features">CC</div>
                          <div class="value_specification"><?php echo $cc ?></div>
                        </div>
                      <?php endif; ?>

                     <!-- Amps -->
                      <?php
                        $amps = $_helper->productAttribute($_product, nl2br($_product->getAmps()), 'amps');
                        if($amps != '') :
                      ?>
                        <div class="col-sm-3">
                          <div class="specification_box">
                            <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/amps.svg">
                          </div>
                          <div class="specification_features">Amps</div>
                          <div class="value_specification"><?php echo $amps ?></div>
                        </div>
                      <?php endif; ?>

                      <!-- Start -->
                      <?php
                        $start = $_helper->productAttribute($_product, nl2br($_product->getStart()), 'start');
                        if($start != '') :
                      ?>
                        <div class="col-sm-3">
                          <div class="specification_box">
                            <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/start.svg">
                          </div>
                          <div class="specification_features">Start</div>
                          <div class="value_specification"><?php echo $start ?></div>
                        </div>
                      <?php endif; ?>

                     <!-- Phase -->
                      <?php
                        $phase = $_helper->productAttribute($_product, nl2br($_product->getPhase()), 'phase');
                        if($phase != '') :
                      ?>
                        <div class="col-sm-3">
                          <div class="specification_box">
                            <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/phase.svg">
                          </div>
                          <div class="specification_features">Phase</div>
                          <div class="value_specification"><?php echo $phase ?></div>
                        </div>
                      <?php endif; ?>

                      <!-- Load Capacity lbs. -->
                      <?php
                        $load_capacity_lbs = $_helper->productAttribute($_product, nl2br($_product->getLoadCapacityLbs()), 'load_capacity_lbs');
                        if($load_capacity_lbs != '') :
                      ?>
                        <div class="col-sm-3">
                          <div class="specification_box">
                            <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/load_capacity.svg">
                          </div>
                          <div class="specification_features">Load Capacity lbs.</div>
                          <div class="value_specification"><?php echo $load_capacity_lbs ?></div>
                        </div>
                          <tr>
                      <?php endif; ?>

                      <!-- Engine -->
                      <?php
                        $engine = $_helper->productAttribute($_product, nl2br($_product->getEngine()), 'engine');
                        if($engine != '') :
                      ?>
                        <div class="col-sm-3">
                          <div class="specification_box">
                            <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/engine.svg">
                          </div>
                          <div class="specification_features">Engine</div>
                          <div class="value_specification"><?php echo $engine ?></div>
                        </div>
                      <?php endif; ?>

                      <!-- HP -->
                      <?php
                        $hp = $_helper->productAttribute($_product, nl2br($_product->getHp()), 'hp');
                        if($hp != '') :
                      ?>
                        <div class="col-sm-3">
                          <div class="specification_box">
                            <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/hp.svg">
                          </div>
                          <div class="specification_features">HP</div>
                          <div class="value_specification"><?php echo $hp ?></div>
                        </div>
                      <?php endif; ?>

                      <!-- Dimensions (L x W x H) -->
                      <?php
                        $dimensions = $_helper->productAttribute($_product, nl2br($_product->getDimensions()), 'dimensions');
                        if($dimensions != '') :
                      ?>
                        <div class="col-sm-3">
                          <div class="specification_box">
                            <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/dimension.svg">
                          </div>
                          <div class="specification_features">Dimensions (L x W x H)</div>
                          <div class="value_specification"><?php echo $dimensions ?></div>
                        </div>
                      <?php endif; ?>

                      <!-- Pump RPM -->
                      <?php
                        $pump_rpm = $_helper->productAttribute($_product, nl2br($_product->getPumpRpm()), 'pump_rpm');
                        if($pump_rpm != '') :
                      ?>
                        <div class="col-sm-3">
                          <div class="specification_box">
                            <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/pumprpm.svg">
                          </div>
                          <div class="specification_features">Pump RPM</div>
                          <div class="value_specification"><?php echo $pump_rpm ?></div>
                        </div>
                      <?php endif; ?>

                      <!-- Water Tank Gallons -->
                      <?php
                        $water_tank_gallons = $_helper->productAttribute($_product, nl2br($_product->getWaterTankGallons()), 'water_tank_gallons');
                        if($water_tank_gallons != '') :
                      ?>
                        <div class="col-sm-3">
                          <div class="specification_box">
                            <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/gallon.svg">
                          </div>
                          <div class="specification_features">Water Tank Gallons</div>
                          <div class="value_specification"><?php echo $water_tank_gallons ?></div>
                        </div>
                      <?php endif; ?>


                      <!-- Voltage -->
                      <?php
                        $voltage = $_helper->productAttribute($_product, nl2br($_product->getVoltage()), 'voltage');
                        if($voltage != '') :
                      ?>
                        <div class="col-sm-3">
                          <div class="specification_box">
                            <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/voltage.svg">
                          </div>
                          <div class="specification_features">Voltage</div>
                          <div class="value_specification"><?php echo $voltage ?></div>
                        </div>
                      <?php endif; ?>

                      <!-- Axle -->
                      <?php
                        $axle = $_helper->productAttribute($_product, nl2br($_product->getAxle()), 'axle');
                        if($axle != '') :
                      ?>
                        <div class="col-sm-3">
                          <div class="specification_box">
                            <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/axle.svg">
                          </div>
                          <div class="specification_features">Axle</div>
                          <div class="value_specification"><?php echo $axle ?></div>
                        </div>
                      <?php endif; ?>

                      <!-- BTU -->
                      <?php
                        $btu = $_helper->productAttribute($_product, nl2br($_product->getBtu()), 'btu');
                        if($btu != '') :
                      ?>
                        <div class="col-sm-3">
                          <div class="specification_box">
                            <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/btu.svg">
                          </div>
                          <div class="specification_features">BTU</div>
                          <div class="value_specification"><?php echo $btu ?></div>
                        </div>
                      <?php endif; ?>

                      <!-- Burner -->
                      <?php
                        $burner = $_helper->productAttribute($_product, nl2br($_product->getBurner()), 'burner');
                        if($burner != '') :
                      ?>
                        <div class="col-sm-3">
                          <div class="specification_box">
                            <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                          </div>
                          <div class="specification_features">Burner</div>
                          <div class="value_specification"><?php echo $burner ?></div>
                        </div>
                      <?php endif; ?>

                      <!--
                        ****** Floor Care Only Specification *******
                      -->

                      <!-- Steam Temp Pressure -->
                      <?php
                        $steam_temp_pressure = $_helper->productAttribute($_product, nl2br($_product->getSteamTempPressure()), 'steam_temp_pressure');
                        if($steam_temp_pressure != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Steam Temp Pressure</div>
                        <div class="value_specification"><?php echo $steam_temp_pressure ?></div>
                      </div>
                      <?php endif; ?>

                      <!-- Pad Diameter -->
                      <?php
                        $pad_diameter = $_helper->productAttribute($_product, nl2br($_product->getPadDiameter()), 'pad_diameter');
                        if($pad_diameter != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Pad Diameter</div>
                        <div class="value_specification"><?php echo $_product->getAttributeText('pad_diameter'); ?></div>
                      </div>
                      <?php endif; ?>

                      <!-- Hose Length Diameter -->
                      <?php
                        $hose_length_diameter = $_helper->productAttribute($_product, nl2br($_product->getHoseLengthDiameter()), 'hose_length_diameter');
                        if($hose_length_diameter != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Hose Length Diameter</div>
                        <div class="value_specification"><?php echo $_product->getAttributeText('hose_length_diameter'); ?></div>
                      </div>
                      <?php endif; ?>

                      <!-- Steam Temp Pressure -->
                      <?php
                        $brush_rotation_speed = $_helper->productAttribute($_product, nl2br($_product->getBrushRotationSpeed()), 'brush_rotation_speed');
                        if($brush_rotation_speed != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Brush Rotation Speed</div>
                        <div class="value_specification"><?php echo $brush_rotation_speed ?></div>
                      </div>
                      <?php endif; ?>


                      <!-- Moisture Recovery Rate -->
                      <?php
                        $moisture_recovery_rate = $_helper->productAttribute($_product, nl2br($_product->getMoistureRecoveryRate()), 'moisture_recovery_rate');
                        if($moisture_recovery_rate != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Moisture Recovery Rate</div>
                        <div class="value_specification"><?php echo $moisture_recovery_rate ?></div>
                      </div>
                      <?php endif; ?>


                      <!-- Wheels -->
                      <?php
                        $wheels = $_helper->productAttribute($_product, nl2br($_product->getWheels()), 'wheels');
                        if($wheels != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Wheels</div>
                        <div class="value_specification"><?php echo $wheels ?></div>
                      </div>
                      <?php endif; ?>
                      

                      <!-- Weight Including Battery -->
                      <?php
                        $weight_including_battery = $_helper->productAttribute($_product, nl2br($_product->getWeightIncludingBattery()), 'weight_including_battery');
                        if($weight_including_battery != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Weight Including Battery</div>
                        <div class="value_specification"><?php echo $weight_including_battery ?></div>
                      </div>
                      <?php endif; ?>

                      <!-- Battery -->
                      <?php
                        $battery = $_helper->productAttribute($_product, nl2br($_product->getBattery()), 'battery');
                        if($battery != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Battery</div>
                        <div class="value_specification"><?php echo $battery ?></div>
                      </div>
                      <?php endif; ?>

                      <!-- Dust Bag -->
                      <?php
                        $dust_bag = $_helper->productAttribute($_product, nl2br($_product->getDustBag()), 'dust_bag');
                        if($dust_bag != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Dust Bag</div>
                        <div class="value_specification"><?php echo $dust_bag ?></div>
                      </div>
                      <?php endif; ?>


                      <!-- Detailed Item Type -->
                      <?php
                        $detailed_item_type = $_helper->productAttribute($_product, nl2br($_product->getDetailedItemType()), 'detailed_item_type');
                        if($detailed_item_type != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Detailed Item Type</div>
                        <div class="value_specification"><?php echo $detailed_item_type ?></div>
                      </div>
                      <?php endif; ?>


                      <!-- Run Time -->
                      <?php
                        $run_time = $_helper->productAttribute($_product, nl2br($_product->getRunTime()), 'run_time');
                        if($run_time != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Run Time</div>
                        <div class="value_specification"><?php echo $_product->getAttributeText('run_time'); ?></div>
                      </div>
                      <?php endif; ?>


                      <!-- Vacuum Motor -->
                      <?php
                        $vacuum_motor = $_helper->productAttribute($_product, nl2br($_product->getVacuumMotor()), 'vacuum_motor');
                        if($vacuum_motor != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Vacuum Motor</div>
                        <div class="value_specification"><?php echo $vacuum_motor ?></div>
                      </div>
                      <?php endif; ?>


                      <!-- Charger Voltage -->
                      <?php
                        $charger_voltage = $_helper->productAttribute($_product, nl2br($_product->getChargerVoltage()), 'charger_voltage');
                        if($charger_voltage != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Charger Voltage</div>
                        <div class="value_specification"><?php echo $_product->getAttributeText('charger_voltage'); ?></div>
                      </div>
                      <?php endif; ?>


                      <!-- Max Area Performance -->
                      <?php
                        $max_area_perform = $_helper->productAttribute($_product, nl2br($_product->getVacuumMotor()), 'max_area_perform');
                        if($max_area_perform != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Max Area Performance</div>
                        <div class="value_specification"><?php echo $max_area_perform ?></div>
                      </div>
                      <?php endif; ?>


                      <!-- Wheel Front -->
                      <?php
                        $wheel_front = $_helper->productAttribute($_product, nl2br($_product->getWheelFront()), 'wheel_front');
                        if($wheel_front != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Wheel Front</div>
                        <div class="value_specification"><?php echo $wheel_front ?></div>
                      </div>
                      <?php endif; ?>

                      <!-- Fan Speed Levels -->
                      <?php
                        $fan_speed_levels = $_helper->productAttribute($_product, nl2br($_product->getFanSpeedLevels()), 'fan_speed_levels');
                        if($fan_speed_levels != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Fan Speed Levels</div>
                        <div class="value_specification"><?php echo $_product->getAttributeText('fan_speed_levels'); ?></div>
                      </div>
                      <?php endif; ?>

                      <!-- Wheels Back -->
                      <?php
                        $wheels_back = $_helper->productAttribute($_product, nl2br($_product->getWheelsBack()), 'wheels_back');
                        if($wheels_back != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Wheels Back</div>
                        <div class="value_specification"><?php echo $wheels_back ?></div>
                      </div>
                      <?php endif; ?>

                      <!-- Working Width Two Side Brooms -->
                      <?php
                        $working_width_two_side_brooms = $_helper->productAttribute($_product, nl2br($_product->getWorkingWidthTwoSideBrooms()), 'working_width_two_side_brooms');
                        if($working_width_two_side_brooms != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Working Width Two Side Brooms</div>
                        <div class="value_specification"><?php echo $working_width_two_side_brooms ?></div>
                      </div>
                      <?php endif; ?>

                      <!-- Air Flow Rating -->
                      <?php
                        $air_flow_rating = $_helper->productAttribute($_product, nl2br($_product->getAirFlowRating()), 'air_flow_rating');
                        if($air_flow_rating != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Air Flow Rating</div>
                        <div class="value_specification"><?php echo $_product->getAttributeText('air_flow_rating'); ?></div>
                      </div>
                      <?php endif; ?>

                      <!-- Operate Time Carpet Hard Surf -->
                      <?php
                        $operate_time_carpet_hard_surf = $_helper->productAttribute($_product, nl2br($_product->getOperateTimeCarpetHardSurf()), 'operate_time_carpet_hard_surf');
                        if($operate_time_carpet_hard_surf != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Operate Time Carpet</div>
                        <div class="value_specification"><?php echo $_product->getAttributeText('operate_time_carpet_hard_surf'); ?></div>
                      </div>
                      <?php endif; ?>

                      <!-- Noise Level -->
                      <?php
                        $noise_level = $_helper->productAttribute($_product, nl2br($_product->getNoiseLevel()), 'noise_level');
                        if($noise_level != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Noise Level</div>
                        <div class="value_specification"><?php echo $noise_level ?></div>
                      </div>
                      <?php endif; ?>

                      <!-- Working Speed -->
                      <?php
                        $working_speed = $_helper->productAttribute($_product, nl2br($_product->getWorkingSpeed()), 'working_speed');
                        if($working_speed != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Working Speed</div>
                        <div class="value_specification"><?php echo $working_speed ?></div>
                      </div>
                      <?php endif; ?>

                      <!-- Motor Rating -->
                      <?php
                        $motor_rating = $_helper->productAttribute($_product, nl2br($_product->getMotorRating()), 'motor_rating');
                        if($motor_rating != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Motor Rating</div>
                        <div class="value_specification"><?php echo $motor_rating ?></div>
                      </div>
                      <?php endif; ?>

                      <!-- Electric Rating -->
                      <?php
                        $electric_rating = $_helper->productAttribute($_product, nl2br($_product->getElectricRating()), 'electric_rating');
                        if($electric_rating != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Electric Rating</div>
                        <div class="value_specification"><?php echo $_product->getAttributeText('electric_rating'); ?></div>
                      </div>
                      <?php endif; ?>

                      <!-- Power Cable -->
                      <?php
                        $power_cable = $_helper->productAttribute($_product, nl2br($_product->getPowerCable()), 'power_cable');
                        if($power_cable != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Power Cable</div>
                        <div class="value_specification"><?php echo $power_cable ?></div>
                      </div>
                      <?php endif; ?>

                    <!-- Heater -->
                      <?php
                        $heater = $_helper->productAttribute($_product, nl2br($_product->getHeater()), 'heater');
                        if($heater != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Heater</div>
                        <div class="value_specification"><?php echo $heater ?></div>
                      </div>
                      <?php endif; ?>


                      <!-- Battery Capacity -->
                      <?php
                        $battery_capacity = $_helper->productAttribute($_product, nl2br($_product->getBatteryCapacity()), 'battery_capacity');
                        if($battery_capacity != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Battery Capacity</div>
                        <div class="value_specification"><?php echo $_product->getAttributeText('battery_capacity'); ?></div>
                      </div>
                      <?php endif; ?>


                      <!-- Waste Container -->
                      <?php
                        $waste_container = $_helper->productAttribute($_product, nl2br($_product->getWasteContainer()), 'waste_container');
                        if($waste_container != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Waste Container</div>
                        <div class="value_specification"><?php echo $_product->getAttributeText('waste_container'); ?></div>
                      </div>
                      <?php endif; ?>


                      <!-- Power Supply -->
                      <?php
                        $power_supply = $_helper->productAttribute($_product, nl2br($_product->getPowerSupply()), 'power_supply');
                        if($power_supply != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Power Supply</div>
                        <div class="value_specification"><?php echo $_product->getAttributeText('power_supply'); ?></div>
                      </div>
                      <?php endif; ?>



                      <!-- Battery Charge Time -->
                      <?php
                        $battery_charge_time = $_helper->productAttribute($_product, nl2br($_product->getBatteryChargeTime()), 'battery_charge_time');
                        if($battery_charge_time != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Battery Charge Time</div>
                        <div class="value_specification"><?php echo $_product->getAttributeText('battery_charge_time'); ?></div>
                      </div>
                      <?php endif; ?>



                      <!-- Power Rating Fan Pump -->
                      <?php
                        $power_rating_fan_pump = $_helper->productAttribute($_product, nl2br($_product->getPowerRatingFanPump()), 'power_rating_fan_pump');
                        if($power_rating_fan_pump != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Power Rating Fan Pump</div>
                        <div class="value_specification"><?php echo $_product->getAttributeText('power_rating_fan_pump'); ?></div>
                      </div>
                      <?php endif; ?>


                      <!-- Brush Cont Press Disc Roller -->
                      <?php
                        $brush_cont_press_disc_roller = $_helper->productAttribute($_product, nl2br($_product->getBrushContPressDiscRoller()), 'brush_cont_press_disc_roller');
                        if($brush_cont_press_disc_roller != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Brush Content Press Disc Roller</div>
                        <div class="value_specification"><?php echo $_product->getAttributeText('brush_cont_press_disc_roller'); ?></div>
                      </div>
                      <?php endif; ?>


                      <!-- Brush Contact Pressure -->
                      <?php
                        $brush_contact_pressure = $_helper->productAttribute($_product, nl2br($_product->getBrushContactPressure()), 'brush_contact_pressure');
                        if($brush_contact_pressure != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Brush Contact Pressure</div>
                        <div class="value_specification"><?php echo $_product->getAttributeText('brush_contact_pressure'); ?></div>
                      </div>
                      <?php endif; ?>


                      <!-- Waterlift Rating -->
                      <?php
                        $waterlift_rating = $_helper->productAttribute($_product, nl2br($_product->getWaterliftRating()), 'waterlift_rating');
                        if($waterlift_rating != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Waterlift Rating</div>
                        <div class="value_specification"><?php echo $_product->getAttributeText('waterlift_rating'); ?></div>
                      </div>
                      <?php endif; ?>


                      <!-- Climbing Ability -->
                      <?php
                        $climbing_ability = $_helper->productAttribute($_product, nl2br($_product->getClimbingAbility()), 'climbing_ability');
                        if($climbing_ability != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Climbing Ability</div>
                        <div class="value_specification"><?php echo $_product->getAttributeText('climbing_ability'); ?></div>
                      </div>
                      <?php endif; ?>



                      <!-- Sweeping Method -->
                      <?php
                        $sweeping_method = $_helper->productAttribute($_product, nl2br($_product->getSweepingMethod()), 'sweeping_method');
                        if($sweeping_method != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Sweeping Method</div>
                        <div class="value_specification"><?php echo $_product->getAttributeText('sweeping_method'); ?></div>
                      </div>
                      <?php endif; ?>




                      <!-- Construction -->
                      <?php
                        $construction = $_helper->productAttribute($_product, nl2br($_product->getConstruction()), 'construction');
                        if($construction != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Construction</div>
                        <div class="value_specification"><?php echo $_product->getAttributeText('construction'); ?></div>
                      </div>
                      <?php endif; ?>


                      <!-- Hand Tube -->
                      <?php
                        $hand_tube = $_helper->productAttribute($_product, nl2br($_product->getHandTube()), 'hand_tube');
                        if($hand_tube != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Hand Tube</div>
                        <div class="value_specification"><?php echo $_product->getAttributeText('hand_tube'); ?></div>
                      </div>
                      <?php endif; ?>


                      <!-- Motor -->
                      <?php
                        $motor = $_helper->productAttribute($_product, nl2br($_product->getMotor()), 'motor');
                        if($motor != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Motor</div>
                        <div class="value_specification"><?php echo $_product->getAttributeText('motor'); ?></div>
                      </div>
                      <?php endif; ?>


                      <!-- Brush Rotation Speed Disc Roller -->
                      <?php
                        $brush_rotate_speed_disc_roller = $_helper->productAttribute($_product, nl2br($_product->getBrushRotateSpeedDiscRoller()), 'brush_rotate_speed_disc_roller');
                        if($brush_rotate_speed_disc_roller != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Brush Rotation Speed Disc Roller</div>
                        <div class="value_specification"><?php echo $_product->getAttributeText('brush_rotate_speed_disc_roller'); ?></div>
                      </div>
                      <?php endif; ?>


                      <!-- Brushes -->
                      <?php
                        $brushes = $_helper->productAttribute($_product, nl2br($_product->getBrushes()), 'brushes');
                        if($brushes != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Brushes</div>
                        <div class="value_specification"><?php echo $_product->getAttributeText('brushes'); ?></div>
                      </div>
                      <?php endif; ?>



                      <!-- Pad Working Width -->
                      <?php
                        $pad_working_width = $_helper->productAttribute($_product, nl2br($_product->getPadWorkingWidth()), 'pad_working_width');
                        if($pad_working_width != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Pad Working Width</div>
                        <div class="value_specification"><?php echo $_product->getAttributeText('pad_working_width'); ?></div>
                      </div>
                      <?php endif; ?>


                      <!-- Container Capacity -->
                      <?php
                        $container_capacity = $_helper->productAttribute($_product, nl2br($_product->getContainerCapacity()), 'container_capacity');
                        if($container_capacity != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Container Capacity</div>
                        <div class="value_specification"><?php echo $_product->getAttributeText('container_capacity'); ?></div>
                      </div>
                      <?php endif; ?>


                      <!-- Brush Diameter -->
                      <?php
                        $brush_diameter = $_helper->productAttribute($_product, nl2br($_product->getBrushDiameter()), 'brush_diameter');
                        if($brush_diameter != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Brush Diameter</div>
                        <div class="value_specification"><?php echo $_product->getAttributeText('brush_diameter'); ?></div>
                      </div>
                      <?php endif; ?>

                      <!-- Pad Rotation Speed -->
                      <?php
                        $pad_rotation_speed = $_helper->productAttribute($_product, nl2br($_product->getPadRotationSpeed()), 'pad_rotation_speed');
                        if($pad_rotation_speed != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Pad Rotation Speed</div>
                        <div class="value_specification"><?php echo $_product->getAttributeText('pad_rotation_speed'); ?></div>
                      </div>
                      <?php endif; ?>


                      <!-- Optional Brushes -->
                      <?php
                        $optional_brushes = $_helper->productAttribute($_product, nl2br($_product->getOptionalBrushes()), 'optional_brushes');
                        if($optional_brushes != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Optional Brushes</div>
                        <div class="value_specification"><?php echo $_product->getAttributeText('optional_brushes'); ?></div>
                      </div>
                      <?php endif; ?>


                      <!-- Drive -->
                      <?php
                        $drive = $_helper->productAttribute($_product, nl2br($_product->getDrive()), 'drive');
                        if($drive != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Drive</div>
                        <div class="value_specification"><?php echo $_product->getAttributeText('drive'); ?></div>
                      </div>
                      <?php endif; ?>


                      <!-- Solution Capacity -->
                      <?php
                        $solution_capacity = $_helper->productAttribute($_product, nl2br($_product->getSolutionCapacity()), 'solution_capacity');
                        if($solution_capacity != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Solution Capacity</div>
                        <div class="value_specification"><?php echo $_product->getAttributeText('solution_capacity'); ?></div>
                      </div>
                      <?php endif; ?>



                      <!-- Spray Rate -->
                      <?php
                        $spray_rate = $_helper->productAttribute($_product, nl2br($_product->getSprayRate()), 'spray_rate');
                        if($spray_rate != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Spray Rate</div>
                        <div class="value_specification"><?php echo $_product->getAttributeText('spray_rate'); ?></div>
                      </div>
                      <?php endif; ?>



                      <!-- Vacuum Working Width -->
                      <?php
                        $vacuum_working_width = $_helper->productAttribute($_product, nl2br($_product->getVacuumWorkingWidth()), 'vacuum_working_width');
                        if($vacuum_working_width != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Vacuum Working Width</div>
                        <div class="value_specification"><?php echo $_product->getAttributeText('vacuum_working_width'); ?></div>
                      </div>
                      <?php endif; ?>



                      <!-- Spray Pressure Back Pressure -->
                      <?php
                        $spray_pressure_back_pressure = $_helper->productAttribute($_product, nl2br($_product->getVacuumWorkingWidth()), 'spray_pressure_back_pressure');
                        if($spray_pressure_back_pressure != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Spray Pressure Back Pressure</div>
                        <div class="value_specification"><?php echo $_product->getAttributeText('spray_pressure_back_pressure'); ?></div>
                      </div>
                      <?php endif; ?>


                      <!-- Solution Flow -->
                      <?php
                        $solution_flow = $_helper->productAttribute($_product, nl2br($_product->getSolutionFlow()), 'solution_flow');
                        if($solution_flow != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Solution Flow</div>
                        <div class="value_specification"><?php echo $_product->getAttributeText('solution_flow'); ?></div>
                      </div>
                      <?php endif; ?>


                      <!-- Filtration System -->
                      <?php
                        $filtration_system = $_helper->productAttribute($_product, nl2br($_product->getFiltrationSystem()), 'filtration_system');
                        if($filtration_system != '') :
                      ?>
                        <div class="col-sm-3">
                          <div class="specification_box">
                            <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                          </div>
                          <div class="specification_features">Filtration System</div>
                          <div class="value_specification"><?php echo $_product->getAttributeText('filtration_system'); ?></div>
                        </div>
                      <?php endif; ?>


                      <!-- Practical Area Performance -->
                      <?php
                        $practical_area_performance = $_helper->productAttribute($_product, nl2br($_product->getPracticalAreaPerformance()), 'practical_area_performance');
                        if($practical_area_performance != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Practical Area Performance</div>
                        <div class="value_specification"><?php echo $_product->getAttributeText('practical_area_performance'); ?></div>
                      </div>
                      <?php endif; ?>


                      
                      <!-- Tank Fresh Dirty -->
                      <?php
                        $tank_fresh_dirty = $_helper->productAttribute($_product, nl2br($_product->getTankFreshDirty()), 'tank_fresh_dirty');
                        if($tank_fresh_dirty != '') :
                      ?>
                      <div class="col-sm-3">
                        <div class="specification_box">
                          <img class="img-responsive" src="<?php echo $this->getSkinUrl()?>images/icons/burner.svg">
                        </div>
                        <div class="specification_features">Tank Fresh Dirty</div>
                        <div class="value_specification"><?php echo $_product->getAttributeText('tank_fresh_dirty'); ?></div>
                      </div>
                      <?php endif; ?>




                </div>
            </div>
        </div>
    </section>



    <section class="cta">
        <div class="cta-content">
            <div class="container">
                <h2>Stop Thinking.<br>Start Buying.</h2>
                 <div class="add-to-cart-wrapper">
                    <?php echo $this->getChildHtml('product_type_data') ?>
                    <?php echo $this->getChildHtml('extrahint') ?>

                    <?php if (!$this->hasOptions()):?>
                        <div class="add-to-box">
                            <?php if($_product->isSaleable()): ?>
                                <?php echo $this->getChildHtml('addtocart') ?>
                            <?php endif; ?>
                        </div>
                    <?php elseif (!$_product->isSaleable()): ?>
                        <div class="add-to-box">
                            <?php echo $this->getChildHtml('sharing') ?>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <div class="overlay"></div>
    </section>
    <?php
      $product_brochure_url = $_helper->productAttribute($_product, nl2br($_product->getProductBrochureUrl()), 'product_brochure_url');
      if($product_brochure_url != '') :
    ?>
      <section id="contact" class="contact bg-primary">
          <div class="container">
              <h2>Want to know more?</h2>
              <a href="<?php echo $product_brochure_url ?>" type="button" title="<?php echo $buttonTitle ?>" class="btn btn-outline btn-xl page-scroll" target="_blank"><span><span>See Brochure</span></span></a>
          </div>
      </section>
    <?php endif; ?>
  </form>
<script type="text/javascript">
        //<![CDATA[
            var productAddToCartForm = new VarienForm('product_addtocart_form');
            productAddToCartForm.submit = function(button, url) {
                if (this.validator.validate()) {
                    var form = this.form;
                    var oldUrl = form.action;

                    if (url) {
                       form.action = url;
                    }
                    var e = null;
                    try {
                        this.form.submit();
                    } catch (e) {
                    }
                    this.form.action = oldUrl;
                    if (e) {
                        throw e;
                    }

                    if (button && button != 'undefined') {
                        button.disabled = true;
                    }
                }
            }.bind(productAddToCartForm);

            productAddToCartForm.submitLight = function(button, url){
                if(this.validator) {
                    var nv = Validation.methods;
                    delete Validation.methods['required-entry'];
                    delete Validation.methods['validate-one-required'];
                    delete Validation.methods['validate-one-required-by-name'];
                    // Remove custom datetime validators
                    for (var methodName in Validation.methods) {
                        if (methodName.match(/^validate-datetime-.*/i)) {
                            delete Validation.methods[methodName];
                        }
                    }

                    if (this.validator.validate()) {
                        if (url) {
                            this.form.action = url;
                        }
                        this.form.submit();
                    }
                    Object.extend(Validation.methods, nv);
                }
            }.bind(productAddToCartForm);
        //]]>
        </script>